/**
 *
 *  Account.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Account.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::vkr;

const std::string Account::Cols::_account_id = "\"account_id\"";
const std::string Account::Cols::_email = "\"email\"";
const std::string Account::Cols::_pass_hash = "\"pass_hash\"";
const std::string Account::primaryKeyName = "account_id";
const bool Account::hasPrimaryKey = true;
const std::string Account::tableName = "\"account\"";

const std::vector<typename Account::MetaData> Account::metaData_={
{"account_id","int32_t","integer",4,1,1,1},
{"email","std::string","character varying",256,0,0,1},
{"pass_hash","std::string","character varying",256,0,0,1}
};
const std::string &Account::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Account::Account(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>(r["account_id"].as<int32_t>());
        }
        if(!r["email"].isNull())
        {
            email_=std::make_shared<std::string>(r["email"].as<std::string>());
        }
        if(!r["pass_hash"].isNull())
        {
            passHash_=std::make_shared<std::string>(r["pass_hash"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            accountId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            email_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            passHash_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Account::Account(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            passHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

Account::Account(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("pass_hash"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["pass_hash"].isNull())
        {
            passHash_=std::make_shared<std::string>(pJson["pass_hash"].asString());
        }
    }
}

void Account::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            passHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void Account::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("account_id"))
    {
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("pass_hash"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["pass_hash"].isNull())
        {
            passHash_=std::make_shared<std::string>(pJson["pass_hash"].asString());
        }
    }
}

const int32_t &Account::getValueOfAccountId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(accountId_)
        return *accountId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Account::getAccountId() const noexcept
{
    return accountId_;
}
void Account::setAccountId(const int32_t &pAccountId) noexcept
{
    accountId_ = std::make_shared<int32_t>(pAccountId);
    dirtyFlag_[0] = true;
}
const typename Account::PrimaryKeyType & Account::getPrimaryKey() const
{
    assert(accountId_);
    return *accountId_;
}

const std::string &Account::getValueOfEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(email_)
        return *email_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Account::getEmail() const noexcept
{
    return email_;
}
void Account::setEmail(const std::string &pEmail) noexcept
{
    email_ = std::make_shared<std::string>(pEmail);
    dirtyFlag_[1] = true;
}
void Account::setEmail(std::string &&pEmail) noexcept
{
    email_ = std::make_shared<std::string>(std::move(pEmail));
    dirtyFlag_[1] = true;
}

const std::string &Account::getValueOfPassHash() const noexcept
{
    static const std::string defaultValue = std::string();
    if(passHash_)
        return *passHash_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Account::getPassHash() const noexcept
{
    return passHash_;
}
void Account::setPassHash(const std::string &pPassHash) noexcept
{
    passHash_ = std::make_shared<std::string>(pPassHash);
    dirtyFlag_[2] = true;
}
void Account::setPassHash(std::string &&pPassHash) noexcept
{
    passHash_ = std::make_shared<std::string>(std::move(pPassHash));
    dirtyFlag_[2] = true;
}

void Account::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Account::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "email",
        "pass_hash"
    };
    return inCols;
}

void Account::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPassHash())
        {
            binder << getValueOfPassHash();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Account::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Account::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPassHash())
        {
            binder << getValueOfPassHash();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Account::toJson() const
{
    Json::Value ret;
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getPassHash())
    {
        ret["pass_hash"]=getValueOfPassHash();
    }
    else
    {
        ret["pass_hash"]=Json::Value();
    }
    return ret;
}

Json::Value Account::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAccountId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAccountId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getEmail())
            {
                ret[pMasqueradingVector[1]]=getValueOfEmail();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPassHash())
            {
                ret[pMasqueradingVector[2]]=getValueOfPassHash();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getPassHash())
    {
        ret["pass_hash"]=getValueOfPassHash();
    }
    else
    {
        ret["pass_hash"]=Json::Value();
    }
    return ret;
}

bool Account::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(0, "account_id", pJson["account_id"], err, true))
            return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(1, "email", pJson["email"], err, true))
            return false;
    }
    else
    {
        err="The email column cannot be null";
        return false;
    }
    if(pJson.isMember("pass_hash"))
    {
        if(!validJsonOfField(2, "pass_hash", pJson["pass_hash"], err, true))
            return false;
    }
    else
    {
        err="The pass_hash column cannot be null";
        return false;
    }
    return true;
}
bool Account::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Account::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(0, "account_id", pJson["account_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(1, "email", pJson["email"], err, false))
            return false;
    }
    if(pJson.isMember("pass_hash"))
    {
        if(!validJsonOfField(2, "pass_hash", pJson["pass_hash"], err, false))
            return false;
    }
    return true;
}
bool Account::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Account::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 256)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 256)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 256)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 256)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
